name = "MyHugo"
license = "MIT"
licenselink = "https://github.com/vanvj00003/myhugo/blob/main/LICENSE"
description = "A clean and minimal blog theme for Hugo, based on Hugo Coder"
homepage = "https://github.com/vanvj00003/myhugo/"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal",
  "light",
  "dark",
  "dark mode"
]

features = [
  "analytics",
  "favicon",
  "multilingual",
  "pagination",
  "single-column",
  "syntax-highlighting"
]

min_version = "0.124.0"

[author]
name = "vanvj00003"
homepage = "https://github.com/vanvj00003"
